### ISSUE TITLE
Error running migrate after merging #20

### ISSUE THREAD

**Issue by jtwalters** [proglottis/ladder#21]
The migration introduced in 0770357 seems to be causing problems for me. Perhaps it's an unusual case because one of my tournaments has no ratings? Anyway, I wasn't clever enough this morning to figure it out, but maybe @proglottis knows why. I also use mysql if that matters.

```
 ** [out :: ...] ==  BackpopulatePlayerIdOnRatings: migrating ==================================
 ** [out :: ...] rake aborted!
 ** [out :: ...] An error has occurred, all later migrations canceled:
 ** [out :: ...]
 ** [out :: ...] undefined method `limit' for nil:NilClass
```
